### ISSUE TITLE
Crash in Resource#save

### ISSUE THREAD

**Issue by zedalaye** [mailjet/mailjet-gem#101] opened 2017-06-03 08:14 UTC
My "unsubscribe from lists" code fails since I updated to mailjet-gem 1.5, the problem is still present with 1.5.1 :

```ruby
l = ::Mailjet::Contactslist.all(name: "MyNewsletter", limit: 1).first
lr = ::Mailjet::Listrecipient.all('ContactsList' => l.id, 'Email' => 'me@some.where', limit: 1).first
lr.is_unsubscribed # false
lr.is_unsubscribed = true
lr.is_active = false
lr.save
```

```
ArgumentError: wrong number of arguments (given 0, expected 1)
from /home/pierre/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mailjet-1.5.1/lib/mailjet/resource.rb:246:in `save'
```

**Comment by Zhivko-Mailjet** [comment] 2017-06-05 08:30
@zedalaye 
Thanks for reporting the problem. We will look into it and will get back to you once we have any news.

**Comment by arnaudbreton** [comment] 2017-06-05 09:38
Hi @zedalaye, apologies for the issue. I've just pushed [a branch to stage `v1.5.2`](https://github.com/mailjet/mailjet-gem/tree/prerelease/v1.5.2). Commit https://github.com/mailjet/mailjet-gem/commit/ce2877b5a2599c4cbea333fb7f2fe2f88d3a972e should fix your issue.

Can you please confirm? I'll then release `v1.5.2` with it to Rubygems. Thanks!

Apologies once more for the issue.

**Comment by zedalaye** [comment] 2017-06-05 10:38
As far as I can understand the mailjet-gem code, it looks to me quite impossible for the gem to hit the API when options = {} because of :

```ruby
      def self.default_connection(options = {})
        Mailjet::Connection.new(
          "#{options[:url]}/#{options[:version]}/#{resource_path}",
          options[:api_key] || Mailjet.config.api_key,
          options[:secret_key] || Mailjet.config.secret_key,
          public_operations: public_operations,
          read_only: read_only)
      end
```
Using the debugger, in Mailjet::Connection.initialize, endpoint is "//REST/listrecipient" so it looks like :url and :version must, at least, be specified in order to build a valid URL.

Don't you think this code from Mailjet::Resource#update_attributes should be moved to #save ?

```ruby
    opts = self.class.change_resource_path(options)
    save(opts)
```

**Comment by arnaudbreton** [comment] 2017-06-05 10:46
@zedalaye thanks for your feedback.

Could you show us a full extract of your code (minus your API credentials)? The sample you provided above works me with when I use it this way: 

```ruby
require 'mailjet'

Mailjet.configure do |config|
  config.api_key = ENV['MJ_APIKEY_PUBLIC']
  config.secret_key = ENV['MJ_APIKEY_PRIVATE']
  config.default_from = 'my_registered_mailjet_email@domain.com'
end

l = ::Mailjet::Contactslist.all(limit: 1).first
lr = ::Mailjet::Listrecipient.all('ContactsList' => l.id, 'Email' => 'me@some.where', limit: 1).first
lr.is_unsubscribed # false
lr.is_unsubscribed = true
lr.is_active = false
lr.save
```

**Comment by zedalaye** [comment] 2017-06-05 10:56
All Mailjet subscription/unsubscription code is handled by https://github.com/zedalaye/devise_mailjet/blob/212f7c72ea83e22a9a5936fd56c46dc9f2d43fea/lib/devise_mailjet/mailjet_list_api_mapper.rb later I switched to `lr.update_attributes(is_unsubscribed: true, is_active: false)` (https://github.com/zedalaye/devise_mailjet/blob/master/lib/devise_mailjet/mailjet_list_api_mapper.rb) that works as expetected.

**Comment by arnaudbreton** [comment] 2017-06-05 11:19
@zedalaye thanks for the details, however I'm not sure I'm following if the issue is fixed following my commit mentioned above?

**Comment by zedalaye** [comment] 2017-06-05 12:39
Sorry for not being as clear as you would have expected. No, your commit has not solved my issue. The API call from `lr.save` do not hit the API (because in subsequent `Mailjet::Connection.initialize`, endpoint is `//REST/listrecipient`) so, for now I have to stick with the `update_attributes` version instead of `save`. Can you tell me if I'm clear enough ?

**Comment by arnaudbreton** [comment] 2017-06-05 12:49
@zedalaye now it's clear, thanks! Apologies for the misunderstanding. You say it's only `subsequent` calls which are failing. Does it mean the first call work?

**Comment by zedalaye** [comment] 2017-06-05 13:00
Still not that clear :)

From my `devise_mailjet/mailjet_api_mapper.rb`

The first to the API is : `::Mailjet::Contactslist.all(...)`, it works. These subsenquent calls works too : `::Mailjet::Contactslist.create(...)`, `::Mailjet::Contact.find(email)`, `::Mailjet::Contact.create(email: email)` as do `lr = ::Mailjet::Listrecipient.all('ContactsList' => list_id, 'Contact' =>  contact_id, limit: 1).first`

What don't work is the final `lr.save` from https://github.com/zedalaye/devise_mailjet/blob/212f7c72ea83e22a9a5936fd56c46dc9f2d43fea/lib/devise_mailjet/mailjet_list_api_mapper.rb#L33-L59

I had to switch to `lr.update_attributes()` to make it work.

**Comment by arnaudbreton** [comment] 2017-06-05 13:02
Thanks. Are you sure you're using the wrapper at the right revision? I tested your sample by myself and it now works fine (when I switch back to master branch, it raises the error than yours)

**Comment by zedalaye** [comment] 2017-06-05 13:26
I juts built this straight sample code : https://gist.github.com/zedalaye/3307cca6a94de28f180570fccd55533f

If you run the code `test-with-save.rb' several times, you'll show that no error is raised **BUT**, the output is always : `Subscribed : Unsubscribe !` instead of swapping from Subscribe <-> Unsubscribe each time the code is run as it happens with `test-with-update-attributes.rb`

**Comment by arnaudbreton** [comment] 2017-06-05 14:40
@zedalaye thanks, your sample code has been indeed very helpful to debug what's going on. If I didn't mess up, https://github.com/mailjet/mailjet-gem/commit/886a46a09d8aaffe16fba4aa0c53451942cd027f should fix your issue

**Comment by zedalaye** [comment] 2017-06-05 15:35
It seems to work as expected right now. Thank you very much !

**Comment by zedalaye** [comment] 2017-06-05 15:43
By the way, this may not be the right place to ask for such a question but... is this workflow the most efficient way to subscribe/unsubscribe a contact (that may exist, or not) to a list (that may exist, or not) ?

**Comment by arnaudbreton** [comment] 2017-06-05 16:03
@zedalaye awesome, glad to hear. I'm one who should thank you, your sample saved me sometimes to troubleshoot efficiently.  

I believe the `/contactslist/:id/managecontact` endpoint might be a bit more efficient by allowing to merge the contact creation and subscription step in 1 call: https://dev.mailjet.com/guides/?ruby#create-contact-and-subscribe-at-once

Also, it'll allow you to use the same methods for different action (subscription, resubscription, unsubscription, removal).

I'm closing this issue now and will proceed with v1.5.2 release.

**Closed by arnaudbreton** 2017-06-05 16:03 UTC
